<?php

// Heading
$_['heading_title']      = 'SpectroCoin';

// Text
$_['text_default_title'] = 'Pay with SpectroCoin';
$_['text_payment']       = 'Payment';
$_['text_success']       = 'Success: You have modified Spectrocoin account details!';
$_['text_on']            = 'On';
$_['text_off']           = 'Off';
$_['text_spectrocoin']   = '<a target="_blank" href="http://www.spectrocoin.com"><img src="view/image/payment/spectrocoin-logo.svg" alt="SpectroCoin" title="SpectroCoin" style="border: 1px solid #EEEEEE;" /></a>';

// Entry
$_['entry_title']        = 'Title:';
$_['entry_project']      = 'Project ID:';
$_['entry_merchant']     = 'Merchant ID:';
$_['entry_display_payments'] = 'Enabled';
$_['entry_private_key']  = 'Private key:';
$_['text_edit']          = 'Edit Spectrocoin';
$_['entry_status']       = 'Status:';
$_['entry_sort_order']   = 'Sort Order:';

// Help
$_['help_callback']      = '';
$_['help_private'] = 'Private key is not shown. If you want to change it, just enter your new private key to text box.';
$_['help_merchant'] = 'Enter your merchant ID. You can find it in your SpectroCoin project settings.';
$_['help_project'] = 'Enter your project ID. You can find it in your SpectroCoin project settings.';
$_['help_status'] = 'If set to \'On\', the Spectrocoin payment method will be enabled on checkout.';

// Text
$_['heading_title']      = 'SpectroCoin';
$_['text_title']         = 'Spectrocoin.com';
$_['text_failure']       = '... Your payment has been cancelled!';
$_['text_failure_wait']  = '<b><span style="color: #FF0000">Please wait...</span></b><br>If you are not automatically re-directed in 10 seconds, please click <a href="%s">here</a>.';
$_['status_checkbox_label'] = 'Status:';

//Introductury text
$_['info_heading'] = '<b>Introduction</b>';
$_['info_desc']    = 'The SpectrCoin plugin allows seamless integration of payment gateways into your Opencart website. To get started, you will need to obtain the essential credentials: Merchant ID, Project ID, and Private Key. These credentials are required to enable secure transactions between your website and the payment gateway. Follow the step-by-step tutorial below to acquire these credentials:';
$_['info_step_1']  =  '1. <a href="https://auth.spectrocoin.com/signup" target="_blank">Sign up</a> for a Spectroin Account.';
$_['info_step_2']  =  '2. <a href="https://auth.spectrocoin.com/login" target="_blank">Log in</a> to your Spectroin account.';
$_['info_step_3']  =  '3. On the dashboard, locate the "<b><a href="https://spectrocoin.com/en/merchants/projects" target="_blank">Business</a></b>" tab and click on it.';
$_['info_step_4']  =  '4. Click on "<b><a href="https://spectrocoin.com/en/merchants/projects/new" target="_blank">New project</a></b>".';
$_['info_step_5']  =  '5. Fill in the project details and select desired settings (settings can be changed).';
$_['info_step_6']  =  '6. The <b>Private</b> and <b>Public keys</b> are obtained from your merchant project settings page. Private key is only displayed once when the project is created, but can be newly generated by pressing on <b>"Generate"</b> button below your Public key field. Copy the newly generated private and public keys and store the private key in module settings.';
$_['info_step_7']  =  '7. Click "<b>Submit</b>" to save the project and then click "<b>Close</b>".';
$_['info_step_8']  =  '8. Select the option "<b><a href = "https://spectrocoin.com/en/merchants/projects">All projects</a></b>" and choose your project.';
$_['info_step_9']  =  '9. In module settings fill the <b>merchant id</b> and <b>project id</b>.';
$_['info_note']    =  '<b>Note:</b> Keep in mind that if you want to use the business services of SpectroCoin, your account has to be verified.';


